### PR TITLE
New icons now with proper plain icons.

### PR DESCRIPTION
**Pull request by pbobbenb**
Reverted and closed my previous pull-request and made a new one with proper plain icons for OS 3.x.
Had RAWB-Info set to discard original icon data, but have changed that now and fixed these icons to look correct on plain OS 3.x installs.

### CODE REVIEW

**Comment by pbobbenb** [comment]
Just about to commit my changes :-)

**Comment by Futaura** [comment]
Me too! :-)

**Comment by Futaura** [comment]
Thanks for these - you'll be pleased to know I'm not going to ask for any more changes :-). I just figured that if we are going to change the icons, even if the old ones have been like that for many years I guess, we may as well do it as perfectly as possible. IIRC, green drawers were the default glowicons at some point in ancient history, but I agree these should be blue now.

I've just got to test them on my A1200 later and I may tweak the positioning if necessary. I want to get this into the 4.9 update, which I'm hoping to release on Friday.

I don't know if you noticed, but I have added a new string in the Installer since your edit, and I may be adding another later today (adding a openssl.cnf to the installation, possibly).

**Comment by pbobbenb** [comment]
I'll have a check later today.

**Review by Futaura — APPROVED** [review]

**Pull request merged**
