### PR TITLE
Updated the Install icon to glow icon, changed all drawers from green…

### PR DESCRIPTION
**Pull request by pbobbenb**
… to standard blue and "forgotten" the positions of the icons, so it will select the best positions itself to avoid icons being on top of each other.

### CODE REVIEW

**Comment by Futaura** [comment]
Have you checked that these icons work on all OS combinations? For example, OS3.1 vanilla, OS3.9, OS3.1.4, OS4 and MorphOS?

**Comment by pbobbenb** [comment]
No, I just thought that since they already were glow/newicon we just continue on that path.
But the best thing would obviously be to have separate icons for all distributions, like YAM does.

**Comment by Futaura** [comment]
Oh, ok - I'll check they're when I get a chance. Obviously, icons are not really critical with AmiSSL, as there are no program icons - the user only really sees them at install time in the majority or cases, and not at all when using AmiUpdate on OS4. So, one set is going to be more than sufficient.

**Comment by pbobbenb** [comment]
Wrote a bit wrong in the commit message, "closing brackets" should be "fold markers". Can't find a way to easily change that, so writing it here instead.

**Comment by Futaura** [comment]
Unfortunately, I've checked the icons and you've trashed the "old image" images from the icons, so they won't show up on OS 3.1. We need to make sure nothing is lost, so I propose the icons are left unchanged.

I am happy to include your install script modifications though, but please add this in a new separate pull request.

**Pull request closed without merging**
