### PR TITLE
Updated swedish translation of the Install script.

### PR DESCRIPTION
**Pull request by pbobbenb**

### CODE REVIEW

**Comment by pbobbenb** [comment]
I see that it wants to merge 10 commits, how do I avoid that?
I selected my own latest local commit and selected Create pull request in Sourcetree for Mac but still it wants to incorporate all history since my first pull request. Do I need to create a new branch every time I make changes to avoid that or??

**Comment by Futaura** [comment]
I'm not 100% sure, but from googling it seems you are supposed to create branches for each pull request, and once a pull request is merged, that branch should then be deleted.

**Comment by jens-maus** [comment]
Yep and welcome to the 21st century ;)

pull requests should usually be submitted on dedicated feature branches in the forked repository and not base a PR on the master branch..

**Comment by Futaura** [comment]
@pbobbenb  Ok, so you should probably move your latest commit onto a new branch and create a new pull request. Otherwise, I'll have to do a squash and merge, which will create a different commit on the main upstream repository, causing your master commits to differ even more than now.

Whatever, you somehow need to sync your forked master so it is not 10 commits ahead of the upstream master (due to me having to squash merge your previous pull request #50 for the icon changes). I won't pretend to know how to do that. Any advice @jens-maus ? Multiple Google searches tend to suggest the following:

```
git checkout master      // origin master
git fetch upstream
git reset --hard upstream/master
git push --force
```

**Comment by jens-maus** [comment]
Squash and merge is totally fine and the usual way. No reason to take care of foreign forks.

**Comment by Futaura** [comment]
@jens-maus Sure, but I figured @pbobbenb would want to sort out his fork master before making any further changes in the future. But, as long as the changes are made on a new branch on the fork in the future, I guess it won't matter to us.

**Pull request closed without merging**
